package:
  name: kafka-backed-dict
  version: {{ environ.get('VERSION', '') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pip
    - ujson
    - confluent-kafka
    - python-rocksdb

  run:
    - python
    - ujson
    - confluent-kafka
    - python-rocksdb

test:
  imports:
    - kafka_backed_dict

about:
  home: https://github.com/ActivisionGameScience/kafka-backed-dict.git
  license:  BSD 3-clause
